export const CATEGORY_CREATE_REQUEST = "CATEGORY_CREATE_REQUEST";
export const CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS";
export const CATEGORY_CREATE_FAIL = "CATEGORY_CREATE_FAIL";
export const CATEGORY_CREATE_RESET = "CATEGORY_CREATE_RESET";

export const CATEGORY_BY_ID_REQUEST = "CATEGORY_BY_ID_REQUEST";
export const CATEGORY_BY_ID_SUCCESS = "CATEGORY_BY_ID_SUCCESS";
export const CATEGORY_BY_ID_FAIL = "CATEGORY_BY_ID_FAIL";

export const CATEGORY_EDIT_BY_ID_REQUEST = "CATEGORY_EDIT_BY_ID_REQUEST";
export const CATEGORY_EDIT_BY_ID_SUCCESS = "CATEGORY_EDIT_BY_ID_SUCCESS";
export const CATEGORY_EDIT_BY_ID_FAIL = "CATEGORY_EDIT_BY_ID_FAIL";

export const CATEGORY_DELETE_BY_ID_REQUEST = "CATEGORY_DELETE_BY_ID_REQUEST";
export const CATEGORY_DELETE_BY_ID_SUCCESS = "CATEGORY_DELETE_BY_ID_SUCCESS";
export const CATEGORY_DELETE_BY_ID_FAIL = "CATEGORY_DELETE_BY_ID_FAIL";

export const CATEGORIES_GET_ALL_REQUEST = "CATEGORIES_GET_ALL_REQUEST";
export const CATEGORIES_GET_ALL_SUCCESS = "CATEGORIES_GET_ALL_SUCCESS";
export const CATEGORIES_GET_ALL_FAIL = "CATEGORIES_GET_ALL_FAIL";
